name: Build

on:
  push:
    branches:

jobs:
  minikube:
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Maven Build
        run: mvn clean verify