name: Publish to Maven Central

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          server-id: ossrh
          server-username: ${{ secrets.OSSRHUSERNAME }}
          server-password: ${{ secrets.OSSRHPASSWORD }}
          gpg-private-key: ${{ secrets.SIGNINGKEY }}
          gpg-passphrase: ${{ secrets.SIGNINGPASSWORD }}
      - name: Maven Build
        run: mvn clean verify deploy -Prelease
